### ISSUE TITLE
Registering still isn't reliable

### ISSUE THREAD

**Issue by AlexEndris** [AlexEndris/tst-middleclick#3]
Trying to use a timer now

**Comment by joshuacant** [comment]
Hi Alex, has the timer been more reliable for you? I was using a timer, then switched to the method referenced in your other closed issue, and now I see you've switched to using the timer like I was. I'm still seeing failures to register and re-register with TST, and so are my users. 

Anyway, I'm on the verge of opening an issue on it with Piro to see if there's a possibility the issue is within TST. I'd like to know at least one other developer is having the same issue, before wasting Piro's time.

**Comment by AlexEndris** [comment]
@joshuacant Actually, by my mistake, as I haven't had my own plugin installed but thought it was the registration bug again, so I've switched to your solution.
To my knowledge, there wasn't a problem with my solution nor with yours. Haven't heard back from anyone stating differently and it works for me on multiple computers, as well.
